### ISSUE TITLE
Requests are sent twice with webug enabled [code.google.com]

### ISSUE THREAD

**Issue by fedosov** [fedosov/webug#8]
Reported by GedroX, Aug 3, 2010

Steps to reproduce the problem
1. Create small PHP script for counter stored in session (see attachment);
2. Request it through browser with webug enabled;
3. Counter is increasing by 2 at once – two requests are called to the file per one request made by user.

Expected result:
Counter should be increasing by step=1.

When switching webug off, problem fades away.

No, this is not a problem with favicon.ico absence. :)

Using Windows XP SP3, Google Chrome 5.0.375.125, Webug 1.2.1.

**Comment by UnquietCode** [comment]
Hi there. What was the actual fix for this issue in the code? I'm having a similar problem with an extension I am currently building.

**Comment by fedosov** [comment]
@UnquietCode unfortunately I can't remember this watching the diff. Maybe that was doubling `HEAD` request or something. Maybe you can show your code?

**Comment by UnquietCode** [comment]
Well after some thorough debugging, it turned out that our extension was creating `<img>` elements programmatically but setting their `src` attribute to `"#"`, which had the effect of querying the host webpage for bogus images. Live and learn I guess. Thanks though.
